use_default_settings: true

server:
  secret_key: "CHANGE_ME_GENERATE_WITH_openssl_rand_-hex_32"
  bind_address: "0.0.0.0"
  port: 8080

search:
  safe_search: 0
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: g
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
  - name: brave
    engine: brave
    shortcut: br
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
